sudo: required
services:
  - docker

before_install:
  - docker build -t lucien/docker-react -f Dockerfile.dev .

script:
  - docker run lucien/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk 
  region: "ap-northeast-1"
  app: "docker"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-885661614159"
  bucket_path: "react-app"
  on:
   branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"